# Generated by Django 5.0.2 on 2024-03-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "saving_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "fixed_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("spending", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
