# Generated by Django 5.0.2 on 2024-03-04 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "saving_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "fixed_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("spending", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "custom_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FinancialData",
        ),
    ]
