# Generated by Django 5.0.2 on 2024-03-12 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0005_transaction_description_alter_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
    ]
