# Generated by Django 5.0.2 on 2024-04-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_dashboard", "0008_alter_transaction_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdashboard",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekly", "Weekly"),
                    ("biweekly", "Bi-weekly"),
                    ("monthly", "Monthly"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userdashboard",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
