# Generated by Django 5.0.2 on 2024-04-09 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_dashboard", "0009_userdashboard_frequency_userdashboard_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdashboard",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
