# Generated by Django 5.0.2 on 2024-04-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_dashboard", "0010_alter_userdashboard_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdashboard",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("Weekly", "Weekly"),
                    ("Bi-weekly", "Bi-weekly"),
                    ("Monthly", "Monthly"),
                ],
                default="weekly",
                max_length=10,
            ),
        ),
    ]
