# Generated by Django 5.0.2 on 2024-04-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_dashboard", "0011_alter_userdashboard_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdashboard",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
