# Generated by Django 5.0.2 on 2024-04-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_dashboard", "0012_userdashboard_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdashboard",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="userdashboard",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("Weekly", "Weekly"),
                    ("Bi-weekly", "Bi-weekly"),
                    ("Monthly", "Monthly"),
                ],
                default="Weekly",
                max_length=10,
            ),
        ),
    ]
