# Generated by Django 5.0.3 on 2024-04-20 20:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_dashboard", "0013_userdashboard_total_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdashboard",
            name="fixed_percentage",
        ),
    ]
