# Generated by Django 5.0.3 on 2024-04-23 01:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_dashboard", "0014_remove_userdashboard_fixed_percentage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdashboard",
            old_name="salary",
            new_name="pay_amount",
        ),
    ]
