# Generated by Django 5.0.2 on 2024-03-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0004_alter_userprofile_is_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(
                blank=True, upload_to="user_profile/profile_pictures/"
            ),
        ),
    ]
